// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPXiQ4TbiQkjzq2LE7gP8g3tIUGsQk78E',
    appId: '1:1011471065468:web:8a9ad8da9ea099a7a144f9',
    messagingSenderId: '1011471065468',
    projectId: 'eren-15846',
    authDomain: 'eren-15846.firebaseapp.com',
    storageBucket: 'eren-15846.firebasestorage.app',
    measurementId: 'G-7SLQ09FK3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC08iEpBnm3cDpD6SE1A9XYspmaB77YfAU',
    appId: '1:1011471065468:android:9b252b977192a5f1a144f9',
    messagingSenderId: '1011471065468',
    projectId: 'eren-15846',
    storageBucket: 'eren-15846.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk_9Atgta7o9Tsgr3yeR432oR8p9U-7wM',
    appId: '1:1011471065468:ios:e3f6823def40faa0a144f9',
    messagingSenderId: '1011471065468',
    projectId: 'eren-15846',
    storageBucket: 'eren-15846.firebasestorage.app',
    iosBundleId: 'com.example.eren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk_9Atgta7o9Tsgr3yeR432oR8p9U-7wM',
    appId: '1:1011471065468:ios:e3f6823def40faa0a144f9',
    messagingSenderId: '1011471065468',
    projectId: 'eren-15846',
    storageBucket: 'eren-15846.firebasestorage.app',
    iosBundleId: 'com.example.eren',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPXiQ4TbiQkjzq2LE7gP8g3tIUGsQk78E',
    appId: '1:1011471065468:web:c84886789bc7eb8ca144f9',
    messagingSenderId: '1011471065468',
    projectId: 'eren-15846',
    authDomain: 'eren-15846.firebaseapp.com',
    storageBucket: 'eren-15846.firebasestorage.app',
    measurementId: 'G-517NBTVE68',
  );
}
